export const styles = {
  // 'video-container': 'player_video-container__ndwL-',
  'video-container': 'video-container',
  // 'video-wrapper': 'player_video-wrapper__zkaDS',
  'video-wrapper': 'video-wrapper',

  // 'video-controls': 'toolbar_video-controls__z6g6I',
  'video-controls': 'video-controls',
  // 'video-controls-hidden': 'toolbar_video-controls-hidden__Fyvfe',
  'video-controls-hidden': 'video-controls-hidden',

  // 'video-progress': 'progress_video-progress__QjWkP',
  'video-progress': 'video-progress',
  // 'video-pretime': 'progress_video-pretime__JInJt',
  'video-pretime': 'video-pretime',
  // 'video-buffered': 'progress_video-buffered__N25SV',
  'video-buffered': 'video-buffered',
  // 'video-completed': 'progress_video-completed__CnWX-',
  'video-completed': 'video-completed',
  // 'video-dot': 'progress_video-dot__giuCI',
  'video-dot': 'video-dot',
  // 'video-dot-hidden': 'progress_video-dot-hidden__SceSE',
  'video-dot-hidden': 'video-dot-hidden',

  // 'video-play': 'controller_video-play__fP3BY',
  'video-play': 'video-play',
  // 'video-subplay': 'controller_video-subplay__WTnV2',
  'video-subplay': 'video-subplay',
  // 'video-start-pause': 'controller_video-start-pause__MAW2N',
  'video-start-pause': 'video-start-pause',
  // 'video-duration': 'controller_video-duration__4mxGN',
  'video-duration': 'video-duration',
  // 'video-duration-completed': 'controller_video-duration-completed__aKEo3',
  'video-duration-completed': 'video-duration-completed',
  // 'video-settings': 'controller_video-settings__vL60f',
  'video-settings': 'video-settings',
  // 'video-subsettings': 'controller_video-subsettings__lRckv',
  'video-subsettings': 'video-subsettings',
  // 'video-volume': 'controller_video-volume__6xzJB',
  'video-volume': 'video-volume',
  // 'video-volume-progress': 'controller_video-volume-progress__f4U3J',
  'video-volume-progress': 'video-volume-progress',
  // 'video-volume-completed': 'controller_video-volume-completed__R0FaX',
  'video-volume-completed': 'video-volume-completed',
  // 'video-volume-dot': 'pregress_video-dot__giuCI',
  'video-volume-dot': 'video-volume-dot',
  // 'video-fullscreen': 'controller_video-fullscreen__1-aJA',
  'video-fullscreen': 'video-fullscreen',
  // 'video-duration-all': 'controller_video-duration-all__MOXNR',
  'video-duration-all': 'video-duration-all',
  
  'loading-mask': 'loading-mask',
  'loading-container': 'loading-container',
  'loading-item': 'loading-item',
  'loading-title': 'loading-title',
  'error-mask': 'error-mask',
  'error-container': 'error-container',
  'error-item': 'error-item',
  'error-title': 'error-title'
}
